-- =============================================================================
-- TripMind — lược đồ cơ sở dữ liệu
-- =============================================================================
-- Lược đồ do Flyway quản lý, nằm ở:
--
--     backend/src/main/resources/db/migration/
--
-- V1__baseline.sql là toàn bộ lược đồ v2.0 trước đây nằm trong file này.
-- Mỗi thay đổi sau đó là một file V<n>__<mô_tả>.sql mới. Không sửa migration đã chạy.
--
-- Ứng dụng tự chạy migration khi khởi động. CSDL cũ đã có sẵn bảng thì Flyway nhận
-- làm mốc V1 (baseline-on-migrate) rồi chỉ chạy các migration từ V2 trở đi.
-- =============================================================================
